CREATE TABLE tasks (
id INTEGER PRIMARY KEY AUTOINCREMENT,
description VARCHAR NOT NULL,
created_at DATETIME NOT NULL,
completed_at DATETIME,
priority
);

CREATE TABLE tags (
id INTEGER PRIMARY KEY AUTOINCREMENT,
tag VARCHAR NOT NULL
);

CREATE TABLE tags_tasks (
id INTEGER PRIMARY KEY AUTOINCREMENT,
tag_id INTEGER NOT NULL,
task_id INTEGER NOT NULL,
FOREIGN KEY (tag_id) REFERENCES 'tags' ('id'),
FOREIGN KEY (task_id) REFERENCES 'tasks' ('id')
);

